server:
  port: 8083

spring:
  application:
    name: family-demo
  datasource:
    url: jdbc:mysql://localhost:3306/family?serverTimezone=UTC
    username: root
    password: bingchan
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis配置
